services:
  - type: web
    name: rema-meta-ads-mcp
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: META_ACCESS_TOKEN
        value: EABBMSKgZCZC6YBRZADBoBtNpaJtmdfFyFLeW89oeJJBteaJrwU641yuujn60p42SNPdgAU3WZClOtTesZBvgC7RfInxpJkZAiGM6FZCcfGZCnZALxi0sZC7RK2aV0NWMN2FIG9VlODgPnZB7rDSxvyU6l8d5a7SLJk1GrtAZAWzlvoowSxtR9OTYvufZCRt2LTRjeJLlyiwZDZD
      - key: META_AD_ACCOUNT_ID
        value: act_1243052028017945
